services:
  postgres:
    image: postgres:15-alpine
    container_name: techmarket-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: techmarket
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - techmarket-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d techmarket"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  techmarket-network:
    driver: bridge